### ISSUE TITLE
Search in multiple perturbation spaces

### ISSUE THREAD

**Issue by Opdoop** [RishabhMaheshwary/query-attack#1]
Nice work! Sorry I didn't dive into the code. I have a question. It's there a way that we could multiple perturbation spaces for search in multiple perturbation spaces like [SemAttack](https://arxiv.org/abs/2205.01287)?

**Comment by RishabhMaheshwary** [comment]
Hi, The current implementation does not support adding perturbations from multiple search spaces but one can use the CompositeTransformation [here](https://github.com/RishabhMaheshwary/TextAttack/blob/5fdedb1a63bd4799bd6dbb8e929a117896f6a990/textattack/transformations/composite_transformation.py). Although, I am not sure how similar this will be to the multiple perturbations used in [SemAttack](https://arxiv.org/abs/2205.01287).

**Comment by Opdoop** [comment]
Thanks for your quick response. I'll take a look. Really thanks!
